### ISSUE TITLE
Navigating frame was detached

### ISSUE THREAD

**Issue by mukaramkhaleel** [jina-ai/reader#154]
I am trying to access https://www.bestbuy.com/?intl=nosplash I see a failure and system goes down . 

2024-11-07 11:37:10 Which was derived from:
2024-11-07 11:37:10 
2024-11-07 11:37:10 Error: Navigating frame was detached
2024-11-07 11:37:10     at #onFrameDetached (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/LifecycleWatcher.js:100:47)
2024-11-07 11:37:10     ... 5 lines matching cause stack trace ...
2024-11-07 11:37:10     at #onClientDisconnect (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/FrameManager.js:92:42) {
2024-11-07 11:37:10   cause: Error: Navigating frame was detached
2024-11-07 11:37:10       at #onFrameDetached (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/LifecycleWatcher.js:100:47)
2024-11-07 11:37:10       at /app/node_modules/puppeteer-core/lib/cjs/third_party/mitt/mitt.js:62:7
2024-11-07 11:37:10       at Array.map (<anonymous>)
2024-11-07 11:37:10       at Object.emit (/app/node_modules/puppeteer-core/lib/cjs/third_party/mitt/mitt.js:61:20)
2024-11-07 11:37:10       at CdpFrame.emit (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:83:23)
2024-11-07 11:37:10       at #removeFramesRecursively (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/FrameManager.js:444:15)
2024-11-07 11:37:10       at #onClientDisconnect (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/FrameManager.js:92:42),
2024-11-07 11:37:10   readableMessage: 'AssertionFailureError: Failed to goto https://www.bestbuy.com/?intl=nosplash: Error: Navigating frame was detached'

**Comment by nomagick** [comment]
This is one of the occasional errors Reader may sometimes throw.
The root of this issue is linked to the underlying node provided by Google Cloud. Some nodes are not capable of running a sandboxed browser and it crashes. Unfortunately, there's nothing we can do about it.

If you encounter this you can simply retry and there's a 99.5% chance your next request will be landed on another healthy node.
